version: '3.8'

services:
  mongo-1:
    container_name: 'mongo-1-container'
    network_mode: host
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/shared/keyfile.key"] #Starts as part of a replica set and listens for connections from other nodes
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: Mongo
    volumes:
      - 'mongo1data:/data/db' #Default directory to store data
      - 'mongo1config:/data/configdb' #Used to store metadata
      - '/data/shared:/data/shared' #Shared volume to store keyfile - Bind mount to host's /data/shared directory
    healthcheck: #Connectivity test
      test: ["CMD", "mongosh", "-u", "admin", "-p", "admin123", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s 
    restart: unless-stopped
    user: "mongodb:mongodb" #In order to be able to access Keyfile

volumes:
  mongo1data:
  mongo1config: