version: '3.8'

services:
  mongo-3:
    container_name: 'mongo-3-container'
    network_mode: host
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - 'mongo3data:/data/db'
      - 'mongo3config:/data/configdb'
      - '/data/shared:/data/shared'  # Bind mount to host's /data/shared directory
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/shared/keyfile.key"]
    restart: unless-stopped
    user: "mongodb:mongodb" #In order to be able to access Keyfile

volumes:
  mongo3data:
  mongo3config: