version: '3.8'

services:
  mongo-2:
    container_name: "mongo-2-container"
    network_mode: host
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - 'mongo2data:/data/db'
      - 'mongo2config:/data/configdb'
      - '/data/shared:/data/shared'  # Bind mount to host's /data/shared directory
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/data/shared/keyfile.key"]
    restart: unless-stopped
    user: "mongodb:mongodb" #In order to be able to access Keyfile

volumes:
  mongo2data:
  mongo2config: